services:
  - type: web
    name: arcs-backend
    env: docker
    plan: free
    region: oregon
    dockerFilePath: Dockerfile
    envVars:
      - key: PORT
        value: 7860
      - key: GOOGLE_API_KEY
        sync: true
      - key: GOOGLE_API_KEY_2
        sync: true
      - key: TAVILY_API_KEY
        sync: true
      - key: GROQ_API_KEY
        sync: true
      - key: GROQ_API_KEY_2
        sync: true
      - key: MONGODB_URI
        sync: true


