name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config lfs.allowincompletepush true
          git config --global credential.helper store
          echo "https://itzSiva1:$HF_TOKEN@huggingface.co" > ~/.git-credentials
          git push --force https://itzSiva1:$HF_TOKEN@huggingface.co/spaces/itzSiva1/AdvancedMultiAgentSystem main
